spring:
  profiles:
    active:
      -  dog
      -  EN
      -  prod
#    active: dog,EN,qa

com:
  rs:
    username: YMLUserName
    password: YMLPassword
    jdbcurl: YMLURL
---
spring:
  profiles: prod
com:
  rs:
    username: PROD_YMLUserName
    password: PROD_YMLPassword
    jdbcurl: PROD_YMLURL